#!/bin/sh

if [ "Darwin" != `uname -s` ]; then exit 1 ;fi  

username=$1
if [ ${username:-x} = x ]; then exit 1 ;fi

/usr/bin/dscl /Search -read /Users/${username} dsAttrTypeNative:sshPublicKey  2>/dev/null | /usr/bin/awk 'NR > 1'
